"use client"

import Head from "next/head";

const HeadComponent = () => {
    return (
        <Head>
        <title>Hola desde head</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
    );
};

export default HeadComponent;